export let donuts = [
  {
    id: 1,
    name: "Camel Caramel",
    description: "keep it oldschool",
    img: "/img/brown.png",
    price: "8.99",
    amount: 0,
  },
  {
    id: 2,
    name: "Rednose Rhubarb",
    description: "get sticky wit it",
    img: "/img/red.png",
    price: "7.50",
    amount: 0,
  },
  {
    id: 3,
    name: "Unicorn",
    description: "it's magic",
    img: "/img/pink.png",
    price: "10.50",
    amount: 0,
  },
  {
    id: 4,
    name: "Lemon Submarine",
    description: "on board sailor!",
    img: "/img/striped.png",
    price: "7.50",
    amount: 0,
  },
  {
    id: 5,
    name: "Chess KO",
    description: "don't overthink it",
    img: "/img/bw.png",
    price: "9.45",
    amount: 0,
  },
];
